routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'CustomerController@index');
Route::resource('customer', 'CustomerController');
Route::get('customer/{account}/deposit', 'AccountController@depositView')->name('account.depositview');
Route::get('customer/{account}/widraw', 'AccountController@widrawView')->name('account.widrawview');;
Route::post('customer/{account}/deposit', 'AccountController@deposit')->name('account.deposit');
Route::post('customer/{account}/widraw', 'AccountController@widraw')->name('account.widraw');;

app/Account.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Account extends Model
{
    protected $guarded = [];
    
    public function account()
    {
        return $this->hasOne('App\Customer');
    }

}

app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    protected $guarded = [];
}

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $guarded = [];

    public function account()
    {
        return $this->hasOne('App\Account');
    }

    public function country()
    {
        return $this->belongsTo('App\Country');
    }

    public function gender()
    {
        return $this->belongsTo('App\Gender');
    }
}

app/Gender.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gender extends Model
{
    protected $guarded = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use App\Account;
use Illuminate\Http\Request;

class AccountController extends Controller
{

    /**
     * Deposit determined amount.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function depositView(Account $account)
    {
        return view('account.deposit', compact('account'));
    }

    /**
     * Deposit determined amount.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function deposit(Account $account, Request $request)
    {
        $account->amount =  $account->amount + $request->get('amount');
        $account->save();

        return redirect()->back()->with('success', 'Success!');
    }

    /**
     * Deposit determined amount.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function widrawView(Account $account)
    {
        return view('account.widraw', compact('account'));
    }

    /**
     * widraw determined ammount.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function widraw(Account $account, Request $request)
    {
        if ($account->amount - $request->get('amount') >= 0)
        {
            $account->amount =  $account->amount - $request->get('amount');
            $account->save();
            return redirect()->back()->with('success', 'Success!');
        }
        
        return redirect()->back()->with('errors', 'There was an error with this amount to widraw please try again!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CountryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CountryController extends Controller
{
    //
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use App\Account;
use App\Gender;
use App\Country;
use Illuminate\Http\Request;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::with('country')->get();
        return view('customer.list', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries = Country::all();
        $genders = Gender::all();

        return view('customer.create', compact('countries','genders'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'first_name'=>'required',
            'last_name'=>'required',
            'email'=>'required|unique:customers'
        ]);

        $customer = new Customer([
            'firstName' => $request->get('first_name'),
            'lastName' => $request->get('last_name'),
            'email' => $request->get('email'),
            'gender_id' => $request->get('gender'),
            'country_id' => $request->get('country'),
            'bonus' => rand(5,20)
        ]);
        
        $customer->save();

        //needs separation from this controller
        $account = new Account(['amount' => 0.00]);

        $customer->account()->save($account);

        return redirect('/customer')->with('success', 'Customer created!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer = Customer::find($id);
        $countries = Country::all();
        $genders = Gender::all();

        return view('customer.edit', compact('customer','countries','genders'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Customer $customer, Request $request)
    {
        $request->validate([
            'first_name'=>'required',
            'last_name'=>'required',
            'email'=>'required'
        ]);

        $customer->firstName =  $request->get('first_name');
        $customer->lastName = $request->get('last_name');
        $customer->email = $request->get('email');
        $customer->gender_id = $request->get('gender');
        $customer->country_id = $request->get('country');
        $customer->save();

        return redirect('/customer')->with('success', 'Costumer updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customer $customer)
    {
        //not implemented
    }
}

app/Http/Controllers/GenderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class GenderController extends Controller
{
    //
}

resources/views/customer/create.blade.php
@extends('master.base')

@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-1">Add a customer</h1>
    <div>
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    <form method="post" action="{{ route('customer.store') }}">
        @csrf
        <div class="form-row">
            <div class="form-group">    
                <label for="first_name">First Name:</label>
                <input type="text" class="form-control" name="first_name" required/>
            </div>

            <div class="form-group">
                <label for="last_name">Last Name:</label>
                <input type="text" class="form-control" name="last_name" required/>
            </div>
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" name="email" required/>
        </div>
        
        <div class="form-group">
        <label class="form-check-label" for="country">Country:</label>
            <select name="country" class='form-control' required>
                <option value="" selected disabled>Please select..</option>
                @foreach($countries as $country)
                    <option value="{{$country->id}}">{{$country->name}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
        <label class="form-check-label" for="gender">Gender:</label>
            <select name="gender" class='form-control' required>
                <option value="" selected disabled>Please select..</option>
                @foreach($genders as $gender)
                    <option value="{{$gender->id}}">{{$gender->name}}</option>
                @endforeach
            </select> 
        </div> 

        <button type="submit" class="btn btn-primary-outline">Add contact</button>
        <button type="button" class="btn btn-danger-outline" onclick="javascript:history.go(-1);">cancel</button>
    </form>
  </div>
</div>
</div>
@endsection

resources/views/customer/edit.blade.php
@extends('master.base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-1">Update</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('customer.update', $customer->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-row">
            <div class="form-group">    
                <label for="first_name">First Name:</label>
                <input type="text" class="form-control" name="first_name" value="{{ $customer->firstName }}" required/>
            </div>

            <div class="form-group">
                <label for="last_name">Last Name:</label>
                <input type="text" class="form-control" name="last_name" value="{{ $customer->lastName }}" required/>
            </div>
        </div>

        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" name="email" value="{{ $customer->email }}" required/>
        </div>

        <div class="form-group">
        <label class="form-check-label" for="country">Country:</label>
            <select name="country" class='form-control' required>
                <option value="" selected disabled>Please select..</option>
                @foreach($countries as $country)
                    <option value="{{$country->id}}" {{ ( $customer->country_id == $country->id ) ? 'selected' : '' }} >{{$country->name}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
        <label class="form-check-label" for="gender">Gender:</label>
            <select name="gender" class='form-control' required>
                <option value="" selected disabled>Please select..</option>
                @foreach($genders as $gender)
                    <option value="{{$gender->id}}" {{ ( $customer->gender_id == $gender->id ) ? 'selected' : '' }} >{{$gender->name}}</option>
                @endforeach
            </select> 
        </div> 

            <button type="submit" class="btn btn-primary-outline">Update</button>
            <button type="button" class="btn btn-danger-outline" onclick="javascript:history.go(-1);">cancel</button>

        </form>
    </div>
</div>
@endsection

resources/views/customer/list.blade.php
@extends('master.base')

@section('main')
<div class="row">
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      {{ session()->get('success') }}  
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  @endif
</div>
<div class="col-sm-12">
    <h3>Customers List</h3>
    <div>
    <a style="margin: 19px;" href="{{ route('customer.create')}}" class="btn btn-primary">New Costumer</a>
    </div> 
    @if(isset($customers))   
  <table class="table table-striped">
    <thead>
        <tr>
          <td>Name</td>
          <td>Email</td>
          <td>Country</td>
          <td>Actions</td>
          <td class="text-center" colspan='2'>Operations</td>
        </tr>
    </thead>
    <tbody>
        
        @foreach($customers as $customer)
        <tr>
            <td>{{$customer->firstName}} {{$customer->lastName}}</td>
            <td>{{$customer->email}}</td>
            <td>{{$customer->country->name}}</td>
            <td>
                <a href="{{ route('customer.edit',$customer->id)}}" class="btn btn-outline-primary">
                    <i class="fas fa-edit"></i>
                    Edit
                </a>
            </td>
            <td class="text-center"> 
                <a href="{{ route('account.depositview',$customer->id)}}" class="btn btn-outline-secondary">
                    <i class="fas fa-angle-down text-success"></i>
                    Deposit
                </a>
            </td>
            <td class="text-center">
                <a href="{{ route('account.widrawview',$customer->id)}}" class="btn btn-outline-secondary">
                    <i class="fas fa-angle-up text-danger"></i>
                    Widraw
                </a>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
  @else
  <div>No customers to show</div>
 @endif
<div>
</div>
@endsection

resources/views/master/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Fantastic Internal Bank</title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" rel="stylesheet">
</head>
<body>
  <div class="container">
  <nav class="navbar navbar-light">
  <a class="navbar-brand text-center" href="{{ route('customer.index')}}">
  
  <h2> <i class="fas fa-university"></i> Internal Bank<h2>
    </a>
    
    <!-- // menu // -->
  </nav>
  <hr>
    @yield('main')
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/js/all.min.js">
</body>
</html>